zookeeper:
  scale: 3
  retain_ip: true
  health_check:
    port: 2181
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
mesos-master:
  scale: 3
  retain_ip: true
  health_check:
    port: 5050
    interval: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: '/metrics/snapshot'
    response_timeout: 2000
mesos-slave:
  health_check:
    port: 5051
    interval: 5000
    unhealthy_threshold: 2
    healthy_threshold: 2
    request_line: ''
    response_timeout: 3000
