dhcp:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.system: VirtualMachine
  image: rancher/vm-net:v0.2.1
  cap_add:
  - NET_ADMIN
  command: dhcp

tapd:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.system: VirtualMachine
  image: rancher/vm-net:v0.2.1
  net: host
  cap_add:
  - NET_ADMIN
  devices:
  - /dev/net/tun:/dev/net/tun
  volumes:
  - /var/run/rancher:/var/run/rancher
  command: tapd
